In [ ]:
"""
Experiment 1
LABELS=>
  DDoS : 1
BENIGN : 0

"""

In [ ]:
"""
Experiment 1.1
without Feature Selection

"""

In [ ]:
# Reading CSV file
# Library used : pandas

In [1]:
import pandas as pd

In [2]:
Multi_label_dataset = pd.read_csv("E:/Ankit files/IoT23_thesis/Preprocess_BinaryFiles/Multi_label.csv")

In [ ]:
# Labels and varraiable information in the file displayed

In [3]:
cnt_types = Multi_label_dataset['Label'].value_counts()
print(cnt_types)

2    43606
3    37384
1    35098
0    31381
Name: Label, dtype: int64


In [4]:
Multi_label_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 147469 entries, 0 to 147468
Data columns (total 64 columns):
 #   Column                      Non-Null Count   Dtype  
---  ------                      --------------   -----  
 0   Flow Duration               147469 non-null  int64  
 1   Total Fwd Packet            147469 non-null  int64  
 2   Total Bwd packets           147469 non-null  int64  
 3   Total Length of Fwd Packet  147469 non-null  int64  
 4   Total Length of Bwd Packet  147469 non-null  int64  
 5   Fwd Packet Length Max       147469 non-null  int64  
 6   Fwd Packet Length Min       147469 non-null  int64  
 7   Fwd Packet Length Mean      147469 non-null  float64
 8   Fwd Packet Length Std       147469 non-null  float64
 9   Bwd Packet Length Max       147469 non-null  int64  
 10  Bwd Packet Length Min       147469 non-null  int64  
 11  Bwd Packet Length Mean      147469 non-null  float64
 12  Bwd Packet Length Std       147469 non-null  float64
 13  Flow Bytes/s  

In [5]:
Multi_label_dataset.shape

(147469, 64)

In [ ]:
# Accessing independent varriables(Features) and dependent varriables(Labels)

In [6]:
x = Multi_label_dataset.iloc[:, (Multi_label_dataset.columns!='Label')]
y = Multi_label_dataset.iloc[:,-1]

In [ ]:
# Normalization of independent varriables

In [7]:
x_norm = (x-x.mean())/x.std()

In [ ]:
# check for corelation

In [8]:
crr1=x_norm.corr()
crr1.isnull().sum()

Flow Duration                 0
Total Fwd Packet              0
Total Bwd packets             0
Total Length of Fwd Packet    0
Total Length of Bwd Packet    0
                             ..
Active Min                    0
Idle Mean                     0
Idle Std                      0
Idle Max                      0
Idle Min                      0
Length: 63, dtype: int64

In [ ]:
# check for correlation

In [9]:
sd1 = x_norm.std()
print(sd1[0:10])
print(sd1[10:30])
print(sd1[30:60])
print(sd1[60:70])

Flow Duration                 1.0
Total Fwd Packet              1.0
Total Bwd packets             1.0
Total Length of Fwd Packet    1.0
Total Length of Bwd Packet    1.0
Fwd Packet Length Max         1.0
Fwd Packet Length Min         1.0
Fwd Packet Length Mean        1.0
Fwd Packet Length Std         1.0
Bwd Packet Length Max         1.0
dtype: float64
Bwd Packet Length Min     1.0
Bwd Packet Length Mean    1.0
Bwd Packet Length Std     1.0
Flow Bytes/s              1.0
Flow Packets/s            1.0
Flow IAT Mean             1.0
Flow IAT Std              1.0
Flow IAT Max              1.0
Flow IAT Min              1.0
Fwd IAT Total             1.0
Fwd IAT Mean              1.0
Fwd IAT Std               1.0
Fwd IAT Max               1.0
Fwd IAT Min               1.0
Bwd IAT Total             1.0
Bwd IAT Mean              1.0
Bwd IAT Std               1.0
Bwd IAT Max               1.0
Bwd IAT Min               1.0
Fwd Header Length         1.0
dtype: float64
Bwd Header Length         1.0


In [ ]:
# applying ML Models 

In [ ]:
# Dividing in x_train , x_test , y_train and y_test

In [11]:
from sklearn.model_selection import train_test_split
seed = 7
test_size = 0.20
x_train, x_test, y_train, y_test = train_test_split(x_norm, y, test_size=test_size, random_state=seed)

In [ ]:
"""
Experiment 1.1.1
LWGB

"""

In [12]:
from lightgbm import LGBMClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
import datetime
a = datetime.datetime.now().replace(microsecond=0)
model = LGBMClassifier()
model.fit(x_train, y_train)
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
n_scores = cross_val_score(model, x_test, y_test, scoring='accuracy', cv=cv, n_jobs=-1)
# report performance
from numpy import mean
from numpy import std
print('Accuracy: %.3f (%.3f)' % (mean(n_scores), std(n_scores)))
import sklearn.metrics as metrics
y_pred = model.predict(x_test)
print("Accuracy =", metrics.accuracy_score(y_test, y_pred))
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))
b = datetime.datetime.now().replace(microsecond=0)
print(b-a)

Accuracy: 0.999 (0.001)
Accuracy = 0.9996270427883638
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      6320
           1       1.00      1.00      1.00      6956
           2       1.00      1.00      1.00      8684
           3       1.00      1.00      1.00      7534

    accuracy                           1.00     29494
   macro avg       1.00      1.00      1.00     29494
weighted avg       1.00      1.00      1.00     29494

0:00:26


In [ ]:
"""
Experiment 1.1.2
XGBoost

"""

In [13]:
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
import datetime
import sklearn.metrics as metrics

first_time = datetime.datetime.now()
# fit model no training data
model = XGBClassifier()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
print("Accuracy =", metrics.accuracy_score(y_test, y_pred))

cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
n_scores = cross_val_score(model, x_test, y_test, scoring='accuracy', cv=cv, n_jobs=-1)
from numpy import mean
from numpy import std
print('Accuracy: %.3f (%.3f)' % (mean(n_scores), std(n_scores)))
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))
later_time = datetime.datetime.now()
difference = later_time -  first_time
print(difference)

D:\SOFTWARES\Anaconda\lib\site-packages\xgboost\sklearn.py:888: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[14:43:07] WARNING: ..\src\learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
Accuracy = 0.9996609479894216
Accuracy: 0.999 (0.000)
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      6320
           1       1.00      1.00      1.00      6956
           2       1.00      1.00      1.00      8684
           3       1.00      1.00      1.00      7534

    accuracy                           1.00     29494
   macro avg       1.00      1.00      1.00     29494
weighted avg       1.00      1.00      1.00     29494

0:02:49.144905


In [ ]:
"""
Experiment 1.1.3
DeepForest

"""

In [14]:
import numpy
x_train=x_train.values
y_train=y_train.values
x_test=x_test.values
y_test=y_test.values

In [15]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
import datetime
import sklearn.metrics as metrics


from deepforest import CascadeForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [16]:
first_time = datetime.datetime.now()
model = CascadeForestClassifier( )
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
acc = accuracy_score(y_test,  y_pred) * 100
print("\nTesting Accuracy: {:.3f} %".format(acc))
later_time = datetime.datetime.now()
difference = later_time - first_time
print(difference)

[2021-11-21 09:16:20.922] Start to fit the model:
[2021-11-21 09:16:20.922] Fitting cascade layer = 0 
[2021-11-21 09:16:49.705] layer = 0  | Val Acc = 99.918 % | Elapsed = 28.783 s
[2021-11-21 09:16:49.894] Fitting cascade layer = 1 
[2021-11-21 09:17:12.325] layer = 1  | Val Acc = 99.930 % | Elapsed = 22.431 s
[2021-11-21 09:17:12.486] Fitting cascade layer = 2 
[2021-11-21 09:17:35.121] layer = 2  | Val Acc = 99.928 % | Elapsed = 22.635 s
[2021-11-21 09:17:35.121] Early stopping counter: 1 out of 2
[2021-11-21 09:17:35.309] Fitting cascade layer = 3 
[2021-11-21 09:17:59.330] layer = 3  | Val Acc = 99.914 % | Elapsed = 24.021 s
[2021-11-21 09:17:59.331] Early stopping counter: 2 out of 2
[2021-11-21 09:17:59.331] Handling early stopping
[2021-11-21 09:17:59.333] The optimal number of layers: 2
[2021-11-21 09:17:59.338] Start to evalute the model:
[2021-11-21 09:17:59.387] Evaluating cascade layer = 0 
[2021-11-21 09:18:00.176] Evaluating cascade layer = 1 

Testing Accuracy: 99.949 

In [17]:
c_r = classification_report(y_test, y_pred)
c_m = confusion_matrix(y_test, y_pred)
print(c_r)
print(c_m)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      6320
           1       1.00      1.00      1.00      6956
           2       1.00      1.00      1.00      8684
           3       1.00      1.00      1.00      7534

    accuracy                           1.00     29494
   macro avg       1.00      1.00      1.00     29494
weighted avg       1.00      1.00      1.00     29494

[[6308   12    0    0]
 [   2 6954    0    0]
 [   0    0 8684    0]
 [   1    0    0 7533]]
